language: python
dist: xenial
install: python3 -m pip install tox
script: python3 -m tox
stages:
- test
- PYPI release
jobs:
  include:
  - python: '3.7'
  - python: '3.6'
  - name: 'Python: 3.7'
    os: osx
    osx_image: xcode11
    language: shell
  - name: 'Python: 3.6'
    os: osx
    osx_image: xcode11
    language: shell
    addons:
      homebrew:
        update: true
    before_install:
    - brew unlink python
    - brew install --ignore-dependencies https://raw.githubusercontent.com/Homebrew/homebrew-core/f2a764ef944b1080be64bd88dca9a1d80130c558/Formula/python.rb
    - brew switch python 3.6.5_1
  - name: 'Python: 3.7'
    os: windows
    language: shell
    before_install:
    - choco install python --version 3.7.4
    - python -m pip install --upgrade pip
    install: python -m pip install tox
    script: python -m tox
    env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
  - name: 'Python: 3.6'
    os: windows
    language: shell
    before_install:
    - choco install python --version 3.6.8
    - python -m pip install --upgrade pip
    - python -m pip install pipenv
    install: python -m pip install tox
    script: python -m tox
    env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
  - stage: PYPI release
    language: python
    dist: xenial
    install: pipenv install --dev pipenv-setup
    script: pipenv-setup sync
    after_success: ''
    deploy:
      provider: pypi
      user: Madoshakalaka
      password:
        secure: FO5mp9wbDSamOCnyRf6/SK+UpcoaQqBLUqPr+AWf3qJmymz1p9VaMqNYyYUk2TG02U65ohLKGxlrUrzWpL8gngkBpcSKMo1nHDU1K3nYu3e0ZHOzj3ZPYDHvdjexZrnOeZVuskss1TDrPDGFnsVPyO38O7W6W+VIi+O3iwo4WxcsAJKq6sWV7hlz5T0BTPLiELhe3FspWH+McbAB8GNuIbwKWJe6/5i5yHTZ6vdPskhpQ3RJW86kNDzDI+mEklk6jRfy5irNIfL0nrtqefTvYZIdSj4hc0Rb2LnOaJfoPEgTqT8JqZs0PtQQhueKgekSzLKu8mudeicgs7BJxq4JT+loZtWHdrFVnNvDdhY+wfUCfuJxR7AIwF9rwIAGHzEdOykVNnifXTclYxWl1ILxT7VsAZps44GhBdlhb9n+4zjS9MPnyrFIXQFfzUhRSoOCydZb6+49nGXuAkoGLS7v+Lwj7xmqvzps1o3U6r87l8Lx2YM0pa8m0FdUvjup8kISTHhtWIBSLVBleImOfKc/N1mGotvkO7sKzw281ZxYHDXJP/hrxtU9wDXQl/NVoJuYbW0566iBsUQLCpR10x37MeM2oWjOc1n5SiIgPbNlpXX93oIyK2mQWxTKFS5jrw5P/xIRJ9bL9S/lYh+/qSk7TDIPsjkTWzG0dARcoYxL4Q0=
      on:
        tags: true